dist: trusty
matrix:
  include:
    - language: python
      python: 2.7
      before_install:
        - cd test
      script:
        - python -m unittest discover .

    - language: python
      python: 3.7
      script:
        - python -m unittest discover .
